// <auto-generated />
namespace Core.DataBaseMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreationDateInContest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreationDateInContest));
        
        string IMigrationMetadata.Id
        {
            get { return "201806141322199_CreationDateInContest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
